/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.pharbers.kafka.monitor.schema;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class MonitorResponse extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4534353250999049554L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MonitorResponse\",\"namespace\":\"com.pharbers.kafka.monitor.schema\",\"fields\":[{\"name\":\"connectorName\",\"type\":\"string\"},{\"name\":\"progress\",\"type\":\"long\"},{\"name\":\"error\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence connectorName;
  @Deprecated public long progress;
  @Deprecated public java.lang.CharSequence error;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public MonitorResponse() {}

  /**
   * All-args constructor.
   * @param connectorName The new value for connectorName
   * @param progress The new value for progress
   * @param error The new value for error
   */
  public MonitorResponse(java.lang.CharSequence connectorName, java.lang.Long progress, java.lang.CharSequence error) {
    this.connectorName = connectorName;
    this.progress = progress;
    this.error = error;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return connectorName;
    case 1: return progress;
    case 2: return error;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: connectorName = (java.lang.CharSequence)value$; break;
    case 1: progress = (java.lang.Long)value$; break;
    case 2: error = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'connectorName' field.
   * @return The value of the 'connectorName' field.
   */
  public java.lang.CharSequence getConnectorName() {
    return connectorName;
  }

  /**
   * Sets the value of the 'connectorName' field.
   * @param value the value to set.
   */
  public void setConnectorName(java.lang.CharSequence value) {
    this.connectorName = value;
  }

  /**
   * Gets the value of the 'progress' field.
   * @return The value of the 'progress' field.
   */
  public java.lang.Long getProgress() {
    return progress;
  }

  /**
   * Sets the value of the 'progress' field.
   * @param value the value to set.
   */
  public void setProgress(java.lang.Long value) {
    this.progress = value;
  }

  /**
   * Gets the value of the 'error' field.
   * @return The value of the 'error' field.
   */
  public java.lang.CharSequence getError() {
    return error;
  }

  /**
   * Sets the value of the 'error' field.
   * @param value the value to set.
   */
  public void setError(java.lang.CharSequence value) {
    this.error = value;
  }

  /**
   * Creates a new MonitorResponse RecordBuilder.
   * @return A new MonitorResponse RecordBuilder
   */
  public static com.pharbers.kafka.monitor.schema.MonitorResponse.Builder newBuilder() {
    return new com.pharbers.kafka.monitor.schema.MonitorResponse.Builder();
  }

  /**
   * Creates a new MonitorResponse RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new MonitorResponse RecordBuilder
   */
  public static com.pharbers.kafka.monitor.schema.MonitorResponse.Builder newBuilder(com.pharbers.kafka.monitor.schema.MonitorResponse.Builder other) {
    return new com.pharbers.kafka.monitor.schema.MonitorResponse.Builder(other);
  }

  /**
   * Creates a new MonitorResponse RecordBuilder by copying an existing MonitorResponse instance.
   * @param other The existing instance to copy.
   * @return A new MonitorResponse RecordBuilder
   */
  public static com.pharbers.kafka.monitor.schema.MonitorResponse.Builder newBuilder(com.pharbers.kafka.monitor.schema.MonitorResponse other) {
    return new com.pharbers.kafka.monitor.schema.MonitorResponse.Builder(other);
  }

  /**
   * RecordBuilder for MonitorResponse instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MonitorResponse>
    implements org.apache.avro.data.RecordBuilder<MonitorResponse> {

    private java.lang.CharSequence connectorName;
    private long progress;
    private java.lang.CharSequence error;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.pharbers.kafka.monitor.schema.MonitorResponse.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.connectorName)) {
        this.connectorName = data().deepCopy(fields()[0].schema(), other.connectorName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.progress)) {
        this.progress = data().deepCopy(fields()[1].schema(), other.progress);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.error)) {
        this.error = data().deepCopy(fields()[2].schema(), other.error);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing MonitorResponse instance
     * @param other The existing instance to copy.
     */
    private Builder(com.pharbers.kafka.monitor.schema.MonitorResponse other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.connectorName)) {
        this.connectorName = data().deepCopy(fields()[0].schema(), other.connectorName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.progress)) {
        this.progress = data().deepCopy(fields()[1].schema(), other.progress);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.error)) {
        this.error = data().deepCopy(fields()[2].schema(), other.error);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'connectorName' field.
      * @return The value.
      */
    public java.lang.CharSequence getConnectorName() {
      return connectorName;
    }

    /**
      * Sets the value of the 'connectorName' field.
      * @param value The value of 'connectorName'.
      * @return This builder.
      */
    public com.pharbers.kafka.monitor.schema.MonitorResponse.Builder setConnectorName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.connectorName = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'connectorName' field has been set.
      * @return True if the 'connectorName' field has been set, false otherwise.
      */
    public boolean hasConnectorName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'connectorName' field.
      * @return This builder.
      */
    public com.pharbers.kafka.monitor.schema.MonitorResponse.Builder clearConnectorName() {
      connectorName = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'progress' field.
      * @return The value.
      */
    public java.lang.Long getProgress() {
      return progress;
    }

    /**
      * Sets the value of the 'progress' field.
      * @param value The value of 'progress'.
      * @return This builder.
      */
    public com.pharbers.kafka.monitor.schema.MonitorResponse.Builder setProgress(long value) {
      validate(fields()[1], value);
      this.progress = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'progress' field has been set.
      * @return True if the 'progress' field has been set, false otherwise.
      */
    public boolean hasProgress() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'progress' field.
      * @return This builder.
      */
    public com.pharbers.kafka.monitor.schema.MonitorResponse.Builder clearProgress() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'error' field.
      * @return The value.
      */
    public java.lang.CharSequence getError() {
      return error;
    }

    /**
      * Sets the value of the 'error' field.
      * @param value The value of 'error'.
      * @return This builder.
      */
    public com.pharbers.kafka.monitor.schema.MonitorResponse.Builder setError(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.error = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'error' field has been set.
      * @return True if the 'error' field has been set, false otherwise.
      */
    public boolean hasError() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'error' field.
      * @return This builder.
      */
    public com.pharbers.kafka.monitor.schema.MonitorResponse.Builder clearError() {
      error = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public MonitorResponse build() {
      try {
        MonitorResponse record = new MonitorResponse();
        record.connectorName = fieldSetFlags()[0] ? this.connectorName : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.progress = fieldSetFlags()[1] ? this.progress : (java.lang.Long) defaultValue(fields()[1]);
        record.error = fieldSetFlags()[2] ? this.error : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
